import {
  Wifi,
  Snowflake,
  WashingMachine,
  Refrigerator,
  ArrowUpDown,
  ShieldCheck,
  SquareParking,
  Layers,
  UtensilsCrossed,
  DoorOpen,
  Clock,
  Sofa,
  PawPrint,
  Fingerprint,
  Camera,
} from 'lucide-react';

export const AMENITY_ICONS = {
  WIFI: Wifi,
  MAY_LANH: Snowflake,
  MAY_GIAT: WashingMachine,
  TU_LANH: Refrigerator,
  THANG_MAY: ArrowUpDown,
  BAO_VE_24_24: ShieldCheck,
  HAM_DE_XE: SquareParking,
  GAC: Layers,
  KE_BEP: UtensilsCrossed,
  KHONG_CHUNG_CHU: DoorOpen,
  GIO_GIAC_TU_DO: Clock,
  NOI_THAT_DAY_DU: Sofa,
  CHO_NUOI_THU_CUNG: PawPrint,
  KHOA_VAN_TAY: Fingerprint,
  CAMERA_AN_NINH: Camera,
};
